import os


DATA_SOURCE = os.environ["DATA_SOURCE"]
FITTING_TARGET = os.environ["FITTING_TARGET"]
MODEL_TARGET = os.environ["MODEL_TARGET"]
DATA_RATIO = 1


DATA_BUCKET_NAME = os.environ["DATA_BUCKET_NAME"]
DATA_BUCKET_URI = os.environ["DATA_BUCKET_URI"]

MODEL_BUCKET_NAME = os.environ["MODEL_BUCKET_NAME"]
MODEL_BUCKET_URI = os.environ["MODEL_BUCKET_URI"]

PARAMS_BUCKET_NAME = os.environ["PARAMS_BUCKET_NAME"]
PARAMS_BUCKET_URI = os.environ["PARAMS_BUCKET_URI"]

METRICS_BUCKET_NAME = os.environ["METRICS_BUCKET_NAME"]
METRICS_BUCKET_URI = os.environ["METRICS_BUCKET_URI"]


LOCAL_DATA_PATH = "raw_data"
LOCAL_REGISTRY_PATH =  "pneumonia/training_weights"
